package com.tupi.setup.lexer;

public enum TipoToken {
    NUMERO, TEXTO, VERDADEIRO, FALSO, NULO, IDENTIFICADOR,
    VAR, FUNCAO, RETORNA, SE, SENAO, ENTAO,
    ENQUANTO, PARA, ATE, FACA, FIM, E, OU, NAO,
    ESCREVA, QUEBRA, CONTINUA,
    CLASSE, EU, SUPER, HERDA, DE, METODO,
    TENTA, PEGA, FINALMENTE, LANCA,
    IMPORTE, COMO,
    MAIS, MENOS, MULT, DIV, MOD, POTENCIA,
    IGUAL_IGUAL, DIFERENTE,
    MENOR, MENOR_IGUAL, MAIOR, MAIOR_IGUAL,
    CONCAT, ATRIBUICAO,
    PAREN_ESQ, PAREN_DIR, COLCH_ESQ, COLCH_DIR,
    CHAVE_ESQ, CHAVE_DIR, VIRGULA, PONTO, DOIS_PONTOS,
    NOVA_LINHA, EOF
	}
